-- POVOAMENTO COMPLETO
insert into aluno (numero, nome, email, estatuto, password) values ('a00001', 'Shari Pratty', 'spratty0@answers.com', 1, 'ptlXIJv9dy');
insert into aluno (numero, nome, email, estatuto, password) values ('a00002', 'Chan Lorey', 'clorey1@discovery.com', 0, 'KvC6TJAp');
insert into aluno (numero, nome, email, estatuto, password) values ('a00003', 'Myrwyn Neachell', 'mneachell2@tmall.com', 0, 'Vv1f4CwMaLI');
insert into aluno (numero, nome, email, estatuto, password) values ('a00004', 'Derry Khomich', 'dkhomich3@constantcontact.com', 0, 'W0BdSM5mhZ');
insert into aluno (numero, nome, email, estatuto, password) values ('a00005', 'Zolly Semiras', 'zsemiras4@microsoft.com', 0, 'ZCad5GRRAf2');
insert into aluno (numero, nome, email, estatuto, password) values ('a00006', 'Killian Inkles', 'kinkles5@berkeley.edu', 0, '3gIyFeKri7c2');
insert into aluno (numero, nome, email, estatuto, password) values ('a00007', 'Abelard Kennealy', 'akennealy6@dyndns.org', 1, 'DEhQjrzTId');
insert into aluno (numero, nome, email, estatuto, password) values ('a00008', 'Dmitri Hartness', 'dhartness7@wikia.com', 0, 'YVw3Q6qVQ');
insert into aluno (numero, nome, email, estatuto, password) values ('a00009', 'Shanta Morkham', 'smorkham8@hostgator.com', 0, '8sbOHjH');
insert into aluno (numero, nome, email, estatuto, password) values ('a00010', 'Tedd Aizikowitz', 'taizikowitz9@adobe.com', 0, 'oHisKhwNe5o');
insert into aluno (numero, nome, email, estatuto, password) values ('a00011', 'Alyson Paragreen', 'aparagreena@blogs.com', 0, '5s3kqW6');
insert into aluno (numero, nome, email, estatuto, password) values ('a00012', 'Giovanna Cuddy', 'gcuddyb@senate.gov', 0, '4Om5WB');
insert into aluno (numero, nome, email, estatuto, password) values ('a00013', 'Ashleigh Ferrolli', 'aferrollic@mlb.com', 0, 'EmHYwYldV');
insert into aluno (numero, nome, email, estatuto, password) values ('a00014', 'Nowell Jako', 'njakod@toplist.cz', 0, 'MLqapmLH');
insert into aluno (numero, nome, email, estatuto, password) values ('a00015', 'Thorsten Kuhndel', 'tkuhndele@salon.com', 0, '5wL7GDxCGf');
insert into aluno (numero, nome, email, estatuto, password) values ('a00016', 'Nadia Dymond', 'ndymondf@merriam-webster.com', 0, 'HIvfNAQMycK');
insert into aluno (numero, nome, email, estatuto, password) values ('a00017', 'Craggie Huggins', 'chugginsg@technorati.com', 0, 'G0BYKC5NdgC');
insert into aluno (numero, nome, email, estatuto, password) values ('a00018', 'Krissy Longthorn', 'klongthornh@friendfeed.com', 1, '6S7cDtCgOf');
insert into aluno (numero, nome, email, estatuto, password) values ('a00019', 'Junina Ovey', 'joveyi@liveinternet.ru', 0, 'zpoPWpVnSeEC');
insert into aluno (numero, nome, email, estatuto, password) values ('a00020', 'Devon Mellows', 'dmellowsj@google.es', 0, 'tH6QRl7PpJ');
insert into aluno (numero, nome, email, estatuto, password) values ('a00021', 'Hyacinthie Moorfield', 'hmoorfieldk@4shared.com', 0, 'vrFDQp07');
insert into aluno (numero, nome, email, estatuto, password) values ('a00022', 'Reinald Geroldini', 'rgeroldinil@toplist.cz', 1, 'lwXcAF');
insert into aluno (numero, nome, email, estatuto, password) values ('a00023', 'Ellary Irvine', 'eirvinem@ibm.com', 0, 'IZSek2');
insert into aluno (numero, nome, email, estatuto, password) values ('a00024', 'Cissy MacSwayde', 'cmacswayden@salon.com', 0, 'yl697YpM3Sm');
insert into aluno (numero, nome, email, estatuto, password) values ('a00025', 'Orlan Gosnold', 'ogosnoldo@usgs.gov', 0, 'KIsteKLeo');
insert into aluno (numero, nome, email, estatuto, password) values ('a00026', 'Leesa Ingledow', 'lingledowp@cdc.gov', 0, 'NowDZW');
insert into aluno (numero, nome, email, estatuto, password) values ('a00027', 'Rhianon Lace', 'rlaceq@ucsd.edu', 0, 'AwCL5ttoxPeV');
insert into aluno (numero, nome, email, estatuto, password) values ('a00028', 'Modestine Siddons', 'msiddonsr@desdev.cn', 0, 'TQKGnNFciQ');
insert into aluno (numero, nome, email, estatuto, password) values ('a00029', 'Brunhilde Scarce', 'bscarces@va.gov', 0, '6hK2nu2n');
insert into aluno (numero, nome, email, estatuto, password) values ('a00030', 'Kris Veschi', 'kveschit@pcworld.com', 0, 'Vqf0ApPdg');
insert into aluno (numero, nome, email, estatuto, password) values ('a00031', 'Evan Hartnell', 'ehartnellu@latimes.com', 0, 'YA4FbzdfP');
insert into aluno (numero, nome, email, estatuto, password) values ('a00032', 'Lou Burvill', 'lburvillv@stanford.edu', 0, 'on540PqFmLiA');
insert into aluno (numero, nome, email, estatuto, password) values ('a00033', 'Hieronymus Birchill', 'hbirchillw@zimbio.com', 1, 'H5vVwV');
insert into aluno (numero, nome, email, estatuto, password) values ('a00034', 'Tamarah Luna', 'tlunax@imgur.com', 0, 'CePNTCF8');
insert into aluno (numero, nome, email, estatuto, password) values ('a00035', 'Jefferson Aleksankin', 'jaleksankiny@cyberchimps.com', 0, 'KqrYkObT');
insert into aluno (numero, nome, email, estatuto, password) values ('a00036', 'Leif Death', 'ldeathz@fc2.com', 0, 'pHnw0RcBkn');
insert into aluno (numero, nome, email, estatuto, password) values ('a00037', 'Joan Bucktharp', 'jbucktharp10@foxnews.com', 0, 'yGeYrs4N77s');
insert into aluno (numero, nome, email, estatuto, password) values ('a00038', 'Elvera Byres', 'ebyres11@nyu.edu', 0, '7MC6Fh7xzs6');
insert into aluno (numero, nome, email, estatuto, password) values ('a00039', 'Rickard McAnalley', 'rmcanalley12@flickr.com', 0, '50YEXXk');
insert into aluno (numero, nome, email, estatuto, password) values ('a00040', 'Jessee Blagburn', 'jblagburn13@linkedin.com', 0, 'olb7xeh');
insert into aluno (numero, nome, email, estatuto, password) values ('a00041', 'Demeter Guerrin', 'dguerrin14@wiley.com', 0, 'NA7eRPdMNAyj');
insert into aluno (numero, nome, email, estatuto, password) values ('a00042', 'Inge Honig', 'ihonig15@apple.com', 0, 'OsTZWjQAL8U');
insert into aluno (numero, nome, email, estatuto, password) values ('a00043', 'Arlen Antoniak', 'aantoniak16@imageshack.us', 0, 'dSAeK7JiT5nd');
insert into aluno (numero, nome, email, estatuto, password) values ('a00044', 'Kliment Roskelley', 'kroskelley17@rambler.ru', 0, 'B6XhjJ0jn');
insert into aluno (numero, nome, email, estatuto, password) values ('a00045', 'Silvan Cannicott', 'scannicott18@disqus.com', 0, 'KcHKQu');
insert into aluno (numero, nome, email, estatuto, password) values ('a00046', 'Thibaut Hamlyn', 'thamlyn19@cpanel.net', 0, 'Ontzoh7F');
insert into aluno (numero, nome, email, estatuto, password) values ('a00047', 'Isidro Gossage', 'igossage1a@soundcloud.com', 0, 'sCKYW7GuKv2');
insert into aluno (numero, nome, email, estatuto, password) values ('a00048', 'Merell Bamblett', 'mbamblett1b@wired.com', 0, 'EK9JvulBCx3T');
insert into aluno (numero, nome, email, estatuto, password) values ('a00049', 'Millie Ollerhead', 'mollerhead1c@twitter.com', 0, 'KYCTUsPFC');
insert into aluno (numero, nome, email, estatuto, password) values ('a00050', 'Alverta Indruch', 'aindruch1d@mashable.com', 0, 'f66XYHzH7');
insert into aluno (numero, nome, email, estatuto, password) values ('a00051', 'Constantino Emblem', 'cemblem1e@geocities.com', 0, 'rJdKZ5YyTQB');
insert into aluno (numero, nome, email, estatuto, password) values ('a00052', 'Blondy Rive', 'brive1f@ebay.co.uk', 0, 'xvymsz');
insert into aluno (numero, nome, email, estatuto, password) values ('a00053', 'Saidee McIlhone', 'smcilhone1g@businessweek.com', 0, 'BFjrq2zWtV');
insert into aluno (numero, nome, email, estatuto, password) values ('a00054', 'Chauncey Cammis', 'ccammis1h@purevolume.com', 0, '7WgWYyf');
insert into aluno (numero, nome, email, estatuto, password) values ('a00055', 'Evaleen McCook', 'emccook1i@blog.com', 0, 'VgdangfEmY');
insert into aluno (numero, nome, email, estatuto, password) values ('a00056', 'Aura Zuker', 'azuker1j@meetup.com', 0, 'Fqn5F2WcP');
insert into aluno (numero, nome, email, estatuto, password) values ('a00057', 'Reinald Hellwing', 'rhellwing1k@lulu.com', 0, 'zQIwt4iaK4');
insert into aluno (numero, nome, email, estatuto, password) values ('a00058', 'Solly Grundle', 'sgrundle1l@nifty.com', 0, 'Kh3cjAWySEL');
insert into aluno (numero, nome, email, estatuto, password) values ('a00059', 'Humberto Kimbling', 'hkimbling1m@marriott.com', 0, '4z6Hne');
insert into aluno (numero, nome, email, estatuto, password) values ('a00060', 'Rochelle Jewis', 'rjewis1n@admin.ch', 0, 'iLO6FpN');
insert into aluno (numero, nome, email, estatuto, password) values ('a00061', 'Stanislaus Segges', 'ssegges1o@dedecms.com', 0, 'HfbvVtDzi');
insert into aluno (numero, nome, email, estatuto, password) values ('a00062', 'Salvatore Ibbison', 'sibbison1p@google.pl', 0, 'So8DpKowpn0');
insert into aluno (numero, nome, email, estatuto, password) values ('a00063', 'Sher Ring', 'sring1q@dot.gov', 0, 'ycETLUvJ8t');
insert into aluno (numero, nome, email, estatuto, password) values ('a00064', 'Hakeem Girsch', 'hgirsch1r@elegantthemes.com', 1, 'gX2EuKWt');
insert into aluno (numero, nome, email, estatuto, password) values ('a00065', 'Fidelio Vasenin', 'fvasenin1s@rediff.com', 0, 'rfyMka');
insert into aluno (numero, nome, email, estatuto, password) values ('a00066', 'Crin Eloi', 'celoi1t@bluehost.com', 0, '2brG1Ol');
insert into aluno (numero, nome, email, estatuto, password) values ('a00067', 'Berkley Tydeman', 'btydeman1u@usa.gov', 0, 'pkN8r4lKP');
insert into aluno (numero, nome, email, estatuto, password) values ('a00068', 'Katheryn Crewther', 'kcrewther1v@washingtonpost.com', 1, 'Omj9jM');
insert into aluno (numero, nome, email, estatuto, password) values ('a00069', 'Jo-ann Perritt', 'jperritt1w@irs.gov', 0, 'fIPUjVkeD');
insert into aluno (numero, nome, email, estatuto, password) values ('a00070', 'Burlie Jeffcoate', 'bjeffcoate1x@dot.gov', 0, 'r4qrJSRe');
insert into aluno (numero, nome, email, estatuto, password) values ('a00071', 'Hedwiga Boolsen', 'hboolsen1y@cbsnews.com', 0, 'lK0mm93C');
insert into aluno (numero, nome, email, estatuto, password) values ('a00072', 'Andris Gilby', 'agilby1z@fema.gov', 0, 'f1jhRdE');
insert into aluno (numero, nome, email, estatuto, password) values ('a00073', 'Anjanette Merrikin', 'amerrikin20@weibo.com', 0, 'z4n8oxonrzyz');
insert into aluno (numero, nome, email, estatuto, password) values ('a00074', 'Lanny Shrubsall', 'lshrubsall21@biglobe.ne.jp', 0, 'HvBhccRsi0j8');
insert into aluno (numero, nome, email, estatuto, password) values ('a00075', 'Harv Houseago', 'hhouseago22@nature.com', 0, 'IAmjVGweuLF');
insert into aluno (numero, nome, email, estatuto, password) values ('a00076', 'Viviene Crilley', 'vcrilley23@theguardian.com', 0, 'G1D0M5Qw');
insert into aluno (numero, nome, email, estatuto, password) values ('a00077', 'Candace Franchi', 'cfranchi24@statcounter.com', 0, 'DeqZEnrK3sP');
insert into aluno (numero, nome, email, estatuto, password) values ('a00078', 'Bennie Garbutt', 'bgarbutt25@odnoklassniki.ru', 0, 'waPgVhzilYUz');
insert into aluno (numero, nome, email, estatuto, password) values ('a00079', 'Karil Spraging', 'kspraging26@cnn.com', 0, 'r9sDnJQ');
insert into aluno (numero, nome, email, estatuto, password) values ('a00080', 'Arlyne Boucher', 'aboucher27@issuu.com', 0, 'XNILwWhRMU');
insert into aluno (numero, nome, email, estatuto, password) values ('a00081', 'Jerri Orchart', 'jorchart28@addthis.com', 0, 'cYUvlbqswl6X');
insert into aluno (numero, nome, email, estatuto, password) values ('a00082', 'Nickolaus Tuffs', 'ntuffs29@boston.com', 0, 'siZkmMmh');
insert into aluno (numero, nome, email, estatuto, password) values ('a00083', 'Petronilla Weedall', 'pweedall2a@china.com.cn', 1, 'Pjf5RuxvuJu');
insert into aluno (numero, nome, email, estatuto, password) values ('a00084', 'Eydie Benza', 'ebenza2b@google.co.uk', 0, 'lPvEOWOb');
insert into aluno (numero, nome, email, estatuto, password) values ('a00085', 'Ashla Blamphin', 'ablamphin2c@dailymotion.com', 0, 'sXdsMDic');
insert into aluno (numero, nome, email, estatuto, password) values ('a00086', 'Sophia Goodliffe', 'sgoodliffe2d@fotki.com', 0, 'pXjKg98XAy6p');
insert into aluno (numero, nome, email, estatuto, password) values ('a00087', 'Meier Francescoccio', 'mfrancescoccio2e@eventbrite.com', 0, 'QLtUTgYBpJ96');
insert into aluno (numero, nome, email, estatuto, password) values ('a00088', 'Darcey Harcus', 'dharcus2f@businessinsider.c1om', 0, 'TBH4rKn2uX');
insert into aluno (numero, nome, email, estatuto, password) values ('a00089', 'Andriana MacTeague', 'amacteague2g@baidu.com', 0, 'LGEeTjYEvw1');
insert into aluno (numero, nome, email, estatuto, password) values ('a00090', 'Anjela Anthony', 'aanthony2h@cafepress.com', 0, 'DnmWVe');
insert into aluno (numero, nome, email, estatuto, password) values ('a00091', 'Annalise Astie', 'aastie2i@paypal.com', 1, 'qUzo42V');
insert into aluno (numero, nome, email, estatuto, password) values ('a00092', 'Sheff Reijmers', 'sreijmers2j@archive.org', 0, 'hx8n7AbESz');
insert into aluno (numero, nome, email, estatuto, password) values ('a00093', 'Marcelo Lernihan', 'mlernihan2k@hubpages.com', 0, 'ZUOQ3jLR');
insert into aluno (numero, nome, email, estatuto, password) values ('a00094', 'Clea Wilstead', 'cwilstead2l@pinterest.com', 0, 'S0Ag5JPI80V');
insert into aluno (numero, nome, email, estatuto, password) values ('a00095', 'Saudra Conkay', 'sconkay2m@adobe.com', 0, 'P2C8aek');
insert into aluno (numero, nome, email, estatuto, password) values ('a00096', 'Iain Bilfoot', 'ibilfoot2n@answers.com', 0, 'b3O00OGj');
insert into aluno (numero, nome, email, estatuto, password) values ('a00097', 'Ronny Hallor', 'rhallor2o@adobe.com', 0, 'OVFGXq');
insert into aluno (numero, nome, email, estatuto, password) values ('a00098', 'Fae Edgerley', 'fedgerley2p@nydailynews.com', 0, 'E3KFCn');
insert into aluno (numero, nome, email, estatuto, password) values ('a00099', 'Claire Yanshinov', 'cyanshinov2q@bbc.co.uk', 0, 'fbf8dVdxTii');
insert into aluno (numero, nome, email, estatuto, password) values ('a00100', 'Adolphus Hattigan', 'ahattigan2r@biblegateway.com', 0, 'E6iirJP');
insert into aluno (numero, nome, email, estatuto, password) values ('a00101', 'Faina Ingley', 'fingley2s@tripadvisor.com', 1, '6eQfg8ruDU');
insert into aluno (numero, nome, email, estatuto, password) values ('a00102', 'Marget Lammerich', 'mlammerich2t@msu.edu', 0, 'YqlgnaBLc');
insert into aluno (numero, nome, email, estatuto, password) values ('a00103', 'Stesha Vasilkov', 'svasilkov2u@hibu.com', 0, 'nLUSnlEGydbL');
insert into aluno (numero, nome, email, estatuto, password) values ('a00104', 'Tiffie Portt', 'tportt2v@comsenz.com', 0, 'LnDMCeaEK');
insert into aluno (numero, nome, email, estatuto, password) values ('a00105', 'Cesar Britney', 'cbritney2w@google.pl', 0, 'BEywlUXia');
insert into aluno (numero, nome, email, estatuto, password) values ('a00106', 'Terrie Draisey', 'tdraisey2x@cdbaby.com', 0, 'NYbRqFg9');
insert into aluno (numero, nome, email, estatuto, password) values ('a00107', 'Ula Revie', 'urevie2y@t.co', 0, 'cvUXD3');
insert into aluno (numero, nome, email, estatuto, password) values ('a00108', 'Bernita Antoshin', 'bantoshin2z@ning.com', 0, 'CxpCj1u2MVY');
insert into aluno (numero, nome, email, estatuto, password) values ('a00109', 'Felice Sinnatt', 'fsinnatt30@loc.gov', 0, 'HlbaxyOvR');
insert into aluno (numero, nome, email, estatuto, password) values ('a00110', 'Chariot Hatherell', 'chatherell31@barnesandnoble.com', 0, 'oM2C9kmUgn');
insert into aluno (numero, nome, email, estatuto, password) values ('a00111', 'Carlen de Aguirre', 'cde32@xing.com', 0, '7lgEap');
insert into aluno (numero, nome, email, estatuto, password) values ('a00112', 'Shell Piggott', 'spiggott33@163.com', 0, 'ZUguLJO8a4PX');
insert into aluno (numero, nome, email, estatuto, password) values ('a00113', 'Lulita Greenly', 'lgreenly34@ihg.com', 0, '9uvfXdr');
insert into aluno (numero, nome, email, estatuto, password) values ('a00114', 'Elden Blune', 'eblune35@rambler.ru', 0, '7O5CSJs6U7E');
insert into aluno (numero, nome, email, estatuto, password) values ('a00115', 'Berkeley Petrelluzzi', 'bpetrelluzzi36@barnesandnoble.com', 0, 'Getgbf9');
insert into aluno (numero, nome, email, estatuto, password) values ('a00116', 'Loni Golton', 'lgolton37@paginegialle.it', 0, 'cTheMF');
insert into aluno (numero, nome, email, estatuto, password) values ('a00117', 'Aloysia Spreckley', 'aspreckley38@theguardian.com', 0, 'ZYEjZe');
insert into aluno (numero, nome, email, estatuto, password) values ('a00118', 'Jdavie Paddington', 'jpaddington39@php.net', 1, '5BsufzVlz');
insert into aluno (numero, nome, email, estatuto, password) values ('a00119', 'Stanislaw Victory', 'svictory3a@toplist.cz', 0, 'XBDiTWYsDWC');
insert into aluno (numero, nome, email, estatuto, password) values ('a00120', 'Hana Jaffray', 'hjaffray3b@telegraph.co.uk', 0, 'ddZrDHOj');
insert into aluno (numero, nome, email, estatuto, password) values ('a00121', 'Brier Gauch', 'bgauch3c@kickstarter.com', 0, 'nPweo1Ikj92');
insert into aluno (numero, nome, email, estatuto, password) values ('a00122', 'Phyllida Riglesford', 'priglesford3d@unblog.fr', 1, '0MdlPR0');
insert into aluno (numero, nome, email, estatuto, password) values ('a00123', 'Jermain Stepney', 'jstepney3e@prweb.com', 0, 's0gDtO5I8');
insert into aluno (numero, nome, email, estatuto, password) values ('a00124', 'Quillan Hubery', 'qhubery3f@joomla.org', 0, '9lp2ocz');
insert into aluno (numero, nome, email, estatuto, password) values ('a00125', 'Richie Kiljan', 'rkiljan3g@blogger.com', 0, '6NukoQ');
insert into aluno (numero, nome, email, estatuto, password) values ('a00126', 'Traci Mehaffey', 'tmehaffey3h@pbs.org', 0, 'jW01NF2b0u6B');
insert into aluno (numero, nome, email, estatuto, password) values ('a00127', 'Lydie Dowsey', 'ldowsey3i@jigsy.com', 0, 'hcAcyfMb');
insert into aluno (numero, nome, email, estatuto, password) values ('a00128', 'Kyrstin Learmonth', 'klearmonth3j@mozilla.com', 0, 'BX2KeeFcu7y');
insert into aluno (numero, nome, email, estatuto, password) values ('a00129', 'Boothe Summersby', 'bsummersby3k@technorati.com', 0, '6Q8qPruBNeq');
insert into aluno (numero, nome, email, estatuto, password) values ('a00130', 'Quill Ondrus', 'qondrus3l@ucla.edu', 0, 'QC7B0qu3');
insert into aluno (numero, nome, email, estatuto, password) values ('a00131', 'Jocko Hurd', 'jhurd3m@sitemeter.com', 0, 'eQwTbbj3YdZ');
insert into aluno (numero, nome, email, estatuto, password) values ('a00132', 'Tymothy Reuther', 'treuther3n@rakuten.co.jp', 0, 'LMDAQOZ');
insert into aluno (numero, nome, email, estatuto, password) values ('a00133', 'Ky Jakubovits', 'kjakubovits3o@facebook.com', 0, 'p4NpGaM');
insert into aluno (numero, nome, email, estatuto, password) values ('a00134', 'Chloette Michurin', 'cmichurin3p@timesonline.co.uk', 0, 'ES0LqRiaXIvW');
insert into aluno (numero, nome, email, estatuto, password) values ('a00135', 'Roshelle Chadderton', 'rchadderton3q@netlog.com', 0, 'PkYgiZANqOS');
insert into aluno (numero, nome, email, estatuto, password) values ('a00136', 'Mellicent Biskupski', 'mbiskupski3r@typepad.com', 0, 'jMZsK25P');
insert into aluno (numero, nome, email, estatuto, password) values ('a00137', 'Lulu Wilce', 'lwilce3s@yahoo.com', 1, '1LQwdFT');
insert into aluno (numero, nome, email, estatuto, password) values ('a00138', 'Barron Achromov', 'bachromov3t@youku.com', 0, 't3ArwuC5');
insert into aluno (numero, nome, email, estatuto, password) values ('a00139', 'Tildy Voaden', 'tvoaden3u@java.com', 0, 'YlN4U2Y6');
insert into aluno (numero, nome, email, estatuto, password) values ('a00140', 'Rebekah Roose', 'rroose3v@exblog.jp', 0, 'SgyRrjD2');
insert into aluno (numero, nome, email, estatuto, password) values ('a00141', 'Phylys Humby', 'phumby3w@baidu.com', 1, '56AWxKQV');
insert into aluno (numero, nome, email, estatuto, password) values ('a00142', 'Evangelina Hugland', 'ehugland3x@barnesandnoble.com', 0, '4nn0KgjNmK8');
insert into aluno (numero, nome, email, estatuto, password) values ('a00143', 'Clari Smead', 'csmead3y@vistaprint.com', 0, 'Yd5cv2L');
insert into aluno (numero, nome, email, estatuto, password) values ('a00144', 'Betteann Wreight', 'bwreight3z@github.io', 1, 'Mor6AF4M');
insert into aluno (numero, nome, email, estatuto, password) values ('a00145', 'Lonnie Tinsley', 'ltinsley40@si.edu', 0, 'W452C26s');
insert into aluno (numero, nome, email, estatuto, password) values ('a00146', 'Aline Caudrey', 'acaudrey41@opensource.org', 0, 'HLqFVz7M');
insert into aluno (numero, nome, email, estatuto, password) values ('a00147', 'Darby Daish', 'ddaish42@cafepress.com', 0, 'WtdVCbq');
insert into aluno (numero, nome, email, estatuto, password) values ('a00148', 'Vittoria Benn', 'vbenn43@netlog.com', 0, 'vTrhaY');
insert into aluno (numero, nome, email, estatuto, password) values ('a00149', 'Carleen Mockett', 'cmockett44@squidoo.com', 0, 'HUdZOJ1MCBX');
insert into aluno (numero, nome, email, estatuto, password) values ('a00150', 'Mackenzie Goring', 'mgoring45@freewebs.com', 0, 'PmHXdkn');
insert into aluno (numero, nome, email, estatuto, password) values ('a00151', 'Tiffie Cursey', 'tcursey46@drupal.org', 0, 'tOWpStIHC');
insert into aluno (numero, nome, email, estatuto, password) values ('a00152', 'Storm Gavaghan', 'sgavaghan47@sourceforge.net', 0, 'IknEVZYGm');
insert into aluno (numero, nome, email, estatuto, password) values ('a00153', 'Claudianus Wincom', 'cwincom48@sohu.com', 0, 'B3p7eKq');
insert into aluno (numero, nome, email, estatuto, password) values ('a00154', 'Ly Vautre', 'lvautre49@mapy.cz', 0, 'jxKdC9pIOF0');
insert into aluno (numero, nome, email, estatuto, password) values ('a00155', 'Mireille Plunket', 'mplunket4a@bing.com', 1, 'P09O9inkQk');
insert into aluno (numero, nome, email, estatuto, password) values ('a00156', 'Aarika Axe', 'aaxe4b@flickr.com', 0, 'LHGUHrda');
insert into aluno (numero, nome, email, estatuto, password) values ('a00157', 'Francene Cammack', 'fcammack0@imageshack.us', 0, 'B5KWESrW');
insert into aluno (numero, nome, email, estatuto, password) values ('a00158', 'Petronella Harcus', 'pharcus1@mapquest.com', 1, 'bI9EtAFfh4L');
insert into aluno (numero, nome, email, estatuto, password) values ('a00159', 'Alric MacCorkell', 'amaccorkell2@oakley.com', 0, 'jRs78EstX');
insert into aluno (numero, nome, email, estatuto, password) values ('a00160', 'Gannon Basill', 'gbasill3@mediafire.com', 0, 'CK9ZhC8w');
insert into aluno (numero, nome, email, estatuto, password) values ('a00161', 'Tori Presland', 'tpresland4@instagram.com', 1, 'CStvXoT');
insert into aluno (numero, nome, email, estatuto, password) values ('a00162', 'Jon Munnings', 'jmunnings5@narod.ru', 0, 'VOUoyD');
insert into aluno (numero, nome, email, estatuto, password) values ('a00163', 'Myer Readshall', 'mreadshall6@shareasale.com', 0, '2ApLG7CgTd');
insert into aluno (numero, nome, email, estatuto, password) values ('a00164', 'Marcellus Breem', 'mbreem7@nationalgeographic.com', 1, 'azCwgJsUE');
insert into aluno (numero, nome, email, estatuto, password) values ('a00165', 'Malcolm Wolfers', 'mwolfers8@loc.gov', 1, 'oV3eq6X');
insert into aluno (numero, nome, email, estatuto, password) values ('a00166', 'Erin Mara', 'emara9@4shared.com', 0, 'XLqnX9');
insert into aluno (numero, nome, email, estatuto, password) values ('a00167', 'Wynny Tallquist', 'wtallquista@freewebs.com', 0, 'KGPEiP8PU');
insert into aluno (numero, nome, email, estatuto, password) values ('a00168', 'Mia Daveren', 'mdaverenb@jalbum.net', 0, 'VxqIgsUL');
insert into docente (numero, nome, email, password) values ('b1', 'Natty Dellenbroker', 'ndellenbroker0@example.com', 'qKjXlTKk');
insert into docente (numero, nome, email, password) values ('b2', 'Karlie Reyson', 'kreyson1@t.co', 'jsbEXT28fa2');
insert into docente (numero, nome, email, password) values ('b3', 'Cyndia Czaja', 'cczaja2@pen.io', 'QB7fb2');
insert into docente (numero, nome, email, password) values ('b4', 'Bone Grosier', 'bgrosier3@walmart.com', 'tlPAnumeropUVuq3');
insert into docente (numero, nome, email, password) values ('b5', 'Finlay Bocke', 'fbocke4@dot.gov', 'fsuUdZqhK');
insert into docente (numero, nome, email, password) values ('b6', 'Madalena Dei', 'mdei5@storify.com', 'gyhuhkf');
insert into docente (numero, nome, email, password) values ('b7', 'Kaja Rockell', 'krockell6@msn.com', 'TcFXvN5Y');
insert into docente (numero, nome, email, password) values ('b8', 'Page Raymen', 'praymen7@nydailynews.com', 'KV0yIRRUW');
insert into docente (numero, nome, email, password) values ('b9', 'Dion Gottschalk', 'dgottschalk8@geocities.com', 'nw4NKQg0TXa');
insert into docente (numero, nome, email, password) values ('b10', 'Justine Jandac', 'jjandac9@walmart.com', '78odQwB9kJHJ');
insert into docente (numero, nome, email, password) values ('b11', 'Modesta Kenafaque', 'mkenafaquea@yahoo.co.jp', 'BflGghsvH');
insert into docente (numero, nome, email, password) values ('b12', 'Conrad MacCook', 'cmaccookb@sfgate.com', 'uhA9tgpVEAE');
insert into docente (numero, nome, email, password) values ('b13', 'Freeland Willshere', 'fwillsherec@europa.eu', 'bdcUoOoGz1');
insert into docente (numero, nome, email, password) values ('b14', 'Ronny Skellon', 'rskellond@examiner.com', 'Z412PQVax');
insert into docente (numero, nome, email, password) values ('b15', 'Corilla Cottill', 'ccottille@abc.net.au', '5m3KazZQj');
insert into docente (numero, nome, email, password) values ('b16', 'Alphonse McGaughay', 'amcgaughayf@gravatar.com', 'S0WtksUA');
insert into docente (numero, nome, email, password) values ('b17', 'Langsdon Hiseman', 'lhisemang@dion.ne.jp', 'O87G7eXJk');
insert into docente (numero, nome, email, password) values ('b18', 'Ursuline Verring', 'uverringh@wix.com', 'sQakhbd');
insert into docente (numero, nome, email, password) values ('b19', 'Olga Maggiori', 'omaggiorii@oaic.gov.au', 'kMCrQFs8');
insert into docente (numero, nome, email, password) values ('b20', 'Husain Haydon', 'hhaydonj@paypal.com', 'GwnI6FEPUkfC');
insert into docente (numero, nome, email, password) values ('b21', 'Renard Marfield', 'rmarfieldk@latimes.com', 'J7RCca');
insert into docente (numero, nome, email, password) values ('b22', 'Mariana Bourke', 'mbourkel@ovh.net', 'niUwwDm');
insert into docente (numero, nome, email, password) values ('b23', 'Sully Son', 'ssonm@zimbio.com', 'F3lyOm');
insert into docente (numero, nome, email, password) values ('b24', 'Peadar Grimble', 'pgrimblen@google.es', 'zZpaO19pCx');
insert into docente (numero, nome, email, password) values ('b25', 'Mufinella Forre', 'mforreo@geocities.jp', 'JxLAfoA0');
insert into docente (numero, nome, email, password) values ('b26', 'Shamus Nickerson', 'snickersonp@youku.com', '00xsiSBDU');
insert into docente (numero, nome, email, password) values ('b27', 'Christiano Vuitton', 'cvuittonq@123-reg.co.uk', 'sSfqwUA');
insert into docente (numero, nome, email, password) values ('b28', 'Romain Shallo', 'rshallor@nih.gov', 'v7OFFZHdG');
insert into docente (numero, nome, email, password) values ('b29', 'Teador Deners', 'tdenerss@goo.gl', '46kHY0');
insert into docente (numero, nome, email, password) values ('b30', 'Guthrie Cromly', 'gcromlyt@wikispaces.com', '02VgBmIXm');
insert into docente (numero, nome, email, password) values ('b31', 'Kristian Solley', 'ksolleyu@rediff.com', 'SKxMlLFY7lTF');
insert into docente (numero, nome, email, password) values ('b32', 'Evita Oene', 'eoenev@mashable.com', 'rA3sbzV0rK');
insert into docente (numero, nome, email, password) values ('b33', 'Edeline Francello', 'efrancellow@google.com', 'R4gMV3pkZR9');
insert into docente (numero, nome, email, password) values ('b34', 'Vonni Tembrnumeroge', 'vtembrnumerogex@scientificamerican.com', 'mwbk20');
insert into docente (numero, nome, email, password) values ('b35', 'Donalt Freeman', 'dfreemany@census.gov', 'fQba5W');
insert into docente (numero, nome, email, password) values ('b36', 'Dorothy Melland', 'dmellandz@51.la', '0Impn565');
insert into docente (numero, nome, email, password) values ('b37', 'Siward Hollier', 'shollier10@nyu.edu', 'VvW63K5X');
insert into docente (numero, nome, email, password) values ('b38', 'Melicent Dongles', 'mdongles11@economist.com', 'AIW8mG3irNZ');
insert into docente (numero, nome, email, password) values ('b39', 'Prescott Townsend', 'ptownsend12@sakura.ne.jp', 'msX4t6');
insert into docente (numero, nome, email, password) values ('b40', 'Winslow Gostall', 'wgostall13@xrea.com', 'VMJCg8hqb7T');
insert into docente (numero, nome, email, password) values ('b41', 'Elyssa Merrin', 'emerrin14@eventbrite.com', 'va4010Zdv1C');
insert into docente (numero, nome, email, password) values ('b42', 'Teddy Orum', 'torum15@banumerou.com', 'VsfRgo');
insert into docente (numero, nome, email, password) values ('b43', 'Sheffield Collomosse', 'scollomosse16@europa.eu', 'IhhQ17Zp');
insert into docente (numero, nome, email, password) values ('b44', 'Obnumeroiah Janovsky', 'ojanovsky17@who.int', 'LJ0qYKSZ8');
insert into docente (numero, nome, email, password) values ('b45', 'Neila Bon', 'nbon18@usa.gov', 'XYuLTFrMlQJ');
insert into docente (numero, nome, email, password) values ('b46', 'Jordan Olohan', 'jolohan19@ucla.edu', 'yxlcbPwodX');
insert into docente (numero, nome, email, password) values ('b47', 'Suzann Brydson', 'sbrydson1a@hexun.com', 'l7vIz9kr');
insert into docente (numero, nome, email, password) values ('b48', 'Kate Spring', 'kspring1b@chicagotribune.com', 'ZJKxHqh');
insert into docente (numero, nome, email, password) values ('b49', 'Hedwig Spensly', 'hspensly1c@facebook.com', 'cVDWskowj');
insert into docente (numero, nome, email, password) values ('b50', 'Stanley Cocklie', 'scocklie1d@i2i.jp', 'gG72cA02VO');

insert into direcaoCurso (email, nome, password) values ('dc@di.uminho.pt', 'direção de curso', 'dc');